#############################################################################
# Makefile for building: server
# Generated by qmake (3.1) (Qt 6.6.2)
# Project:  server.pro
# Template: app
# Command: /home/kali/Qt/6.6.2/gcc_64/bin/qmake -o Makefile server.pro -spec linux-clang CONFIG+=qtquickcompiler
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = clang
CXX           = clang++
DEFINES       = -DQT_NO_DEBUG -DQT_NETWORK_LIB -DQT_SQL_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -Wextra -fPIC -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -std=gnu++1z -Wall -Wextra -fPIC -D_REENTRANT $(DEFINES)
INCPATH       = -I. -I../../6.6.2/gcc_64/include -I../../6.6.2/gcc_64/include/QtNetwork -I../../6.6.2/gcc_64/include/QtSql -I../../6.6.2/gcc_64/include/QtCore -I. -I../../6.6.2/gcc_64/mkspecs/linux-clang
QMAKE         = /home/kali/Qt/6.6.2/gcc_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /home/kali/Qt/6.6.2/gcc_64/bin/qmake -install qinstall
QINSTALL_PROGRAM = /home/kali/Qt/6.6.2/gcc_64/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = server1.0.0
DISTDIR = /home/kali/Qt/projects/server/.tmp/server1.0.0
LINK          = clang++
LFLAGS        = -ccc-gcc-name g++ -Wl,-rpath,/home/kali/Qt/6.6.2/gcc_64/lib
LIBS          = $(SUBLIBS) /home/kali/Qt/6.6.2/gcc_64/lib/libQt6Network.so /home/kali/Qt/6.6.2/gcc_64/lib/libQt6Sql.so /home/kali/Qt/6.6.2/gcc_64/lib/libQt6Core.so -lpthread   
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = db_connection.cpp \
		main.cpp \
		server.cpp moc_server.cpp
OBJECTS       = db_connection.o \
		main.o \
		server.o \
		moc_server.o
DIST          = ../../6.6.2/gcc_64/mkspecs/features/spec_pre.prf \
		../../6.6.2/gcc_64/mkspecs/common/unix.conf \
		../../6.6.2/gcc_64/mkspecs/common/linux.conf \
		../../6.6.2/gcc_64/mkspecs/common/sanitize.conf \
		../../6.6.2/gcc_64/mkspecs/common/gcc-base.conf \
		../../6.6.2/gcc_64/mkspecs/common/gcc-base-unix.conf \
		../../6.6.2/gcc_64/mkspecs/common/clang.conf \
		../../6.6.2/gcc_64/mkspecs/qconfig.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_ext_libjpeg.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_ext_libpng.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_core.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_example_icons_private.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_harfbuzz_private.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_help.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_input_support_private.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_jpeg_private.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_kms_support_private.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_labsanimation.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_labsanimation_private.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_labsfolderlistmodel.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_labsqmlmodels.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_labsqmlmodels_private.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_labssettings.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_labssettings_private.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_labssharedimage.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_labssharedimage_private.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_labswavefrontmesh.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_linguist.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_linguist_private.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_network.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_openglwidgets.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_openglwidgets_private.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_png_private.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_qdoccatch_private.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_qdoccatchconversionsprivate.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_qdoccatchconversionsprivate_private.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_qdoccatchgeneratorsprivate.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_qdoccatchgeneratorsprivate_private.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_qmlcompiler.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_qmlcompiler_private.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_qmlcore.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_qmlcore_private.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_qmldom_private.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_qmlintegration.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_qmlintegration_private.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_qmllocalstorage.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_qmllocalstorage_private.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_qmlls_private.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_qmlmodels.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_qmltoolingsettings_private.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_qmltyperegistrar_private.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_qmlxmllistmodel.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_qmlxmllistmodel_private.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_quickcontrols2impl.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_quickcontrolstestutilsprivate_private.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_quickdialogs2.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_quickdialogs2_private.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_quickdialogs2quickimpl.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_quickdialogs2quickimpl_private.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_quickdialogs2utils.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_quickdialogs2utils_private.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_quickeffects_private.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_quicklayouts.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_quicklayouts_private.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_quickshapes_private.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_quicktemplates2.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_quicktestutilsprivate_private.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_svgwidgets.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_svgwidgets_private.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_tools_private.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_wayland_egl_client_hw_integration_private.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_waylandclient.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_waylandclient_private.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_waylandglobal_private.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_wl_shell_integration_private.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../6.6.2/gcc_64/mkspecs/features/qt_functions.prf \
		../../6.6.2/gcc_64/mkspecs/features/qt_config.prf \
		../../6.6.2/gcc_64/mkspecs/linux-clang/qmake.conf \
		../../6.6.2/gcc_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../6.6.2/gcc_64/mkspecs/features/exclusive_builds.prf \
		../../6.6.2/gcc_64/mkspecs/features/toolchain.prf \
		../../6.6.2/gcc_64/mkspecs/features/default_pre.prf \
		../../6.6.2/gcc_64/mkspecs/features/resolve_config.prf \
		../../6.6.2/gcc_64/mkspecs/features/default_post.prf \
		../../6.6.2/gcc_64/mkspecs/features/cmdline.prf \
		../../6.6.2/gcc_64/mkspecs/features/qtquickcompiler.prf \
		../../6.6.2/gcc_64/mkspecs/features/warn_on.prf \
		../../6.6.2/gcc_64/mkspecs/features/permissions.prf \
		../../6.6.2/gcc_64/mkspecs/features/qt.prf \
		../../6.6.2/gcc_64/mkspecs/features/resources_functions.prf \
		../../6.6.2/gcc_64/mkspecs/features/resources.prf \
		../../6.6.2/gcc_64/mkspecs/features/moc.prf \
		../../6.6.2/gcc_64/mkspecs/features/unix/thread.prf \
		../../6.6.2/gcc_64/mkspecs/features/qmake_use.prf \
		../../6.6.2/gcc_64/mkspecs/features/file_copies.prf \
		../../6.6.2/gcc_64/mkspecs/features/testcase_targets.prf \
		../../6.6.2/gcc_64/mkspecs/features/exceptions.prf \
		../../6.6.2/gcc_64/mkspecs/features/yacc.prf \
		../../6.6.2/gcc_64/mkspecs/features/lex.prf \
		server.pro db_connection.h \
		server.h db_connection.cpp \
		main.cpp \
		server.cpp
QMAKE_TARGET  = server
DESTDIR       = 
TARGET        = server


first: all
####### Build rules

server:  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET)  $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: server.pro ../../6.6.2/gcc_64/mkspecs/linux-clang/qmake.conf ../../6.6.2/gcc_64/mkspecs/features/spec_pre.prf \
		../../6.6.2/gcc_64/mkspecs/common/unix.conf \
		../../6.6.2/gcc_64/mkspecs/common/linux.conf \
		../../6.6.2/gcc_64/mkspecs/common/sanitize.conf \
		../../6.6.2/gcc_64/mkspecs/common/gcc-base.conf \
		../../6.6.2/gcc_64/mkspecs/common/gcc-base-unix.conf \
		../../6.6.2/gcc_64/mkspecs/common/clang.conf \
		../../6.6.2/gcc_64/mkspecs/qconfig.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_ext_libjpeg.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_ext_libpng.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_core.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_example_icons_private.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_harfbuzz_private.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_help.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_input_support_private.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_jpeg_private.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_kms_support_private.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_labsanimation.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_labsanimation_private.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_labsfolderlistmodel.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_labsqmlmodels.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_labsqmlmodels_private.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_labssettings.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_labssettings_private.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_labssharedimage.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_labssharedimage_private.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_labswavefrontmesh.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_linguist.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_linguist_private.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_network.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_openglwidgets.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_openglwidgets_private.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_png_private.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_qdoccatch_private.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_qdoccatchconversionsprivate.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_qdoccatchconversionsprivate_private.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_qdoccatchgeneratorsprivate.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_qdoccatchgeneratorsprivate_private.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_qmlcompiler.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_qmlcompiler_private.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_qmlcore.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_qmlcore_private.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_qmldom_private.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_qmlintegration.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_qmlintegration_private.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_qmllocalstorage.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_qmllocalstorage_private.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_qmlls_private.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_qmlmodels.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_qmltoolingsettings_private.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_qmltyperegistrar_private.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_qmlxmllistmodel.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_qmlxmllistmodel_private.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_quickcontrols2impl.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_quickcontrolstestutilsprivate_private.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_quickdialogs2.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_quickdialogs2_private.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_quickdialogs2quickimpl.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_quickdialogs2quickimpl_private.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_quickdialogs2utils.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_quickdialogs2utils_private.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_quickeffects_private.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_quicklayouts.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_quicklayouts_private.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_quickshapes_private.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_quicktemplates2.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_quicktestutilsprivate_private.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_svgwidgets.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_svgwidgets_private.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_tools_private.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_wayland_egl_client_hw_integration_private.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_waylandclient.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_waylandclient_private.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_waylandglobal_private.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_wl_shell_integration_private.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		../../6.6.2/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../6.6.2/gcc_64/mkspecs/features/qt_functions.prf \
		../../6.6.2/gcc_64/mkspecs/features/qt_config.prf \
		../../6.6.2/gcc_64/mkspecs/linux-clang/qmake.conf \
		../../6.6.2/gcc_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../6.6.2/gcc_64/mkspecs/features/exclusive_builds.prf \
		../../6.6.2/gcc_64/mkspecs/features/toolchain.prf \
		../../6.6.2/gcc_64/mkspecs/features/default_pre.prf \
		../../6.6.2/gcc_64/mkspecs/features/resolve_config.prf \
		../../6.6.2/gcc_64/mkspecs/features/default_post.prf \
		../../6.6.2/gcc_64/mkspecs/features/cmdline.prf \
		../../6.6.2/gcc_64/mkspecs/features/qtquickcompiler.prf \
		../../6.6.2/gcc_64/mkspecs/features/warn_on.prf \
		../../6.6.2/gcc_64/mkspecs/features/permissions.prf \
		../../6.6.2/gcc_64/mkspecs/features/qt.prf \
		../../6.6.2/gcc_64/mkspecs/features/resources_functions.prf \
		../../6.6.2/gcc_64/mkspecs/features/resources.prf \
		../../6.6.2/gcc_64/mkspecs/features/moc.prf \
		../../6.6.2/gcc_64/mkspecs/features/unix/thread.prf \
		../../6.6.2/gcc_64/mkspecs/features/qmake_use.prf \
		../../6.6.2/gcc_64/mkspecs/features/file_copies.prf \
		../../6.6.2/gcc_64/mkspecs/features/testcase_targets.prf \
		../../6.6.2/gcc_64/mkspecs/features/exceptions.prf \
		../../6.6.2/gcc_64/mkspecs/features/yacc.prf \
		../../6.6.2/gcc_64/mkspecs/features/lex.prf \
		server.pro \
		../../6.6.2/gcc_64/lib/libQt6Network.prl \
		../../6.6.2/gcc_64/lib/libQt6Sql.prl \
		../../6.6.2/gcc_64/lib/libQt6Core.prl
	$(QMAKE) -o Makefile server.pro -spec linux-clang CONFIG+=qtquickcompiler
../../6.6.2/gcc_64/mkspecs/features/spec_pre.prf:
../../6.6.2/gcc_64/mkspecs/common/unix.conf:
../../6.6.2/gcc_64/mkspecs/common/linux.conf:
../../6.6.2/gcc_64/mkspecs/common/sanitize.conf:
../../6.6.2/gcc_64/mkspecs/common/gcc-base.conf:
../../6.6.2/gcc_64/mkspecs/common/gcc-base-unix.conf:
../../6.6.2/gcc_64/mkspecs/common/clang.conf:
../../6.6.2/gcc_64/mkspecs/qconfig.pri:
../../6.6.2/gcc_64/mkspecs/modules/qt_ext_libjpeg.pri:
../../6.6.2/gcc_64/mkspecs/modules/qt_ext_libpng.pri:
../../6.6.2/gcc_64/mkspecs/modules/qt_lib_concurrent.pri:
../../6.6.2/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../../6.6.2/gcc_64/mkspecs/modules/qt_lib_core.pri:
../../6.6.2/gcc_64/mkspecs/modules/qt_lib_core_private.pri:
../../6.6.2/gcc_64/mkspecs/modules/qt_lib_dbus.pri:
../../6.6.2/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri:
../../6.6.2/gcc_64/mkspecs/modules/qt_lib_designer.pri:
../../6.6.2/gcc_64/mkspecs/modules/qt_lib_designer_private.pri:
../../6.6.2/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../6.6.2/gcc_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
../../6.6.2/gcc_64/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
../../6.6.2/gcc_64/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
../../6.6.2/gcc_64/mkspecs/modules/qt_lib_example_icons_private.pri:
../../6.6.2/gcc_64/mkspecs/modules/qt_lib_fb_support_private.pri:
../../6.6.2/gcc_64/mkspecs/modules/qt_lib_gui.pri:
../../6.6.2/gcc_64/mkspecs/modules/qt_lib_gui_private.pri:
../../6.6.2/gcc_64/mkspecs/modules/qt_lib_harfbuzz_private.pri:
../../6.6.2/gcc_64/mkspecs/modules/qt_lib_help.pri:
../../6.6.2/gcc_64/mkspecs/modules/qt_lib_help_private.pri:
../../6.6.2/gcc_64/mkspecs/modules/qt_lib_input_support_private.pri:
../../6.6.2/gcc_64/mkspecs/modules/qt_lib_jpeg_private.pri:
../../6.6.2/gcc_64/mkspecs/modules/qt_lib_kms_support_private.pri:
../../6.6.2/gcc_64/mkspecs/modules/qt_lib_labsanimation.pri:
../../6.6.2/gcc_64/mkspecs/modules/qt_lib_labsanimation_private.pri:
../../6.6.2/gcc_64/mkspecs/modules/qt_lib_labsfolderlistmodel.pri:
../../6.6.2/gcc_64/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri:
../../6.6.2/gcc_64/mkspecs/modules/qt_lib_labsqmlmodels.pri:
../../6.6.2/gcc_64/mkspecs/modules/qt_lib_labsqmlmodels_private.pri:
../../6.6.2/gcc_64/mkspecs/modules/qt_lib_labssettings.pri:
../../6.6.2/gcc_64/mkspecs/modules/qt_lib_labssettings_private.pri:
../../6.6.2/gcc_64/mkspecs/modules/qt_lib_labssharedimage.pri:
../../6.6.2/gcc_64/mkspecs/modules/qt_lib_labssharedimage_private.pri:
../../6.6.2/gcc_64/mkspecs/modules/qt_lib_labswavefrontmesh.pri:
../../6.6.2/gcc_64/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri:
../../6.6.2/gcc_64/mkspecs/modules/qt_lib_linguist.pri:
../../6.6.2/gcc_64/mkspecs/modules/qt_lib_linguist_private.pri:
../../6.6.2/gcc_64/mkspecs/modules/qt_lib_network.pri:
../../6.6.2/gcc_64/mkspecs/modules/qt_lib_network_private.pri:
../../6.6.2/gcc_64/mkspecs/modules/qt_lib_opengl.pri:
../../6.6.2/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri:
../../6.6.2/gcc_64/mkspecs/modules/qt_lib_openglwidgets.pri:
../../6.6.2/gcc_64/mkspecs/modules/qt_lib_openglwidgets_private.pri:
../../6.6.2/gcc_64/mkspecs/modules/qt_lib_packetprotocol_private.pri:
../../6.6.2/gcc_64/mkspecs/modules/qt_lib_png_private.pri:
../../6.6.2/gcc_64/mkspecs/modules/qt_lib_printsupport.pri:
../../6.6.2/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../../6.6.2/gcc_64/mkspecs/modules/qt_lib_qdoccatch_private.pri:
../../6.6.2/gcc_64/mkspecs/modules/qt_lib_qdoccatchconversionsprivate.pri:
../../6.6.2/gcc_64/mkspecs/modules/qt_lib_qdoccatchconversionsprivate_private.pri:
../../6.6.2/gcc_64/mkspecs/modules/qt_lib_qdoccatchgeneratorsprivate.pri:
../../6.6.2/gcc_64/mkspecs/modules/qt_lib_qdoccatchgeneratorsprivate_private.pri:
../../6.6.2/gcc_64/mkspecs/modules/qt_lib_qml.pri:
../../6.6.2/gcc_64/mkspecs/modules/qt_lib_qml_private.pri:
../../6.6.2/gcc_64/mkspecs/modules/qt_lib_qmlcompiler.pri:
../../6.6.2/gcc_64/mkspecs/modules/qt_lib_qmlcompiler_private.pri:
../../6.6.2/gcc_64/mkspecs/modules/qt_lib_qmlcore.pri:
../../6.6.2/gcc_64/mkspecs/modules/qt_lib_qmlcore_private.pri:
../../6.6.2/gcc_64/mkspecs/modules/qt_lib_qmldebug_private.pri:
../../6.6.2/gcc_64/mkspecs/modules/qt_lib_qmldom_private.pri:
../../6.6.2/gcc_64/mkspecs/modules/qt_lib_qmlintegration.pri:
../../6.6.2/gcc_64/mkspecs/modules/qt_lib_qmlintegration_private.pri:
../../6.6.2/gcc_64/mkspecs/modules/qt_lib_qmllocalstorage.pri:
../../6.6.2/gcc_64/mkspecs/modules/qt_lib_qmllocalstorage_private.pri:
../../6.6.2/gcc_64/mkspecs/modules/qt_lib_qmlls_private.pri:
../../6.6.2/gcc_64/mkspecs/modules/qt_lib_qmlmodels.pri:
../../6.6.2/gcc_64/mkspecs/modules/qt_lib_qmlmodels_private.pri:
../../6.6.2/gcc_64/mkspecs/modules/qt_lib_qmltest.pri:
../../6.6.2/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../../6.6.2/gcc_64/mkspecs/modules/qt_lib_qmltoolingsettings_private.pri:
../../6.6.2/gcc_64/mkspecs/modules/qt_lib_qmltyperegistrar_private.pri:
../../6.6.2/gcc_64/mkspecs/modules/qt_lib_qmlworkerscript.pri:
../../6.6.2/gcc_64/mkspecs/modules/qt_lib_qmlworkerscript_private.pri:
../../6.6.2/gcc_64/mkspecs/modules/qt_lib_qmlxmllistmodel.pri:
../../6.6.2/gcc_64/mkspecs/modules/qt_lib_qmlxmllistmodel_private.pri:
../../6.6.2/gcc_64/mkspecs/modules/qt_lib_quick.pri:
../../6.6.2/gcc_64/mkspecs/modules/qt_lib_quick_private.pri:
../../6.6.2/gcc_64/mkspecs/modules/qt_lib_quickcontrols2.pri:
../../6.6.2/gcc_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
../../6.6.2/gcc_64/mkspecs/modules/qt_lib_quickcontrols2impl.pri:
../../6.6.2/gcc_64/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri:
../../6.6.2/gcc_64/mkspecs/modules/qt_lib_quickcontrolstestutilsprivate_private.pri:
../../6.6.2/gcc_64/mkspecs/modules/qt_lib_quickdialogs2.pri:
../../6.6.2/gcc_64/mkspecs/modules/qt_lib_quickdialogs2_private.pri:
../../6.6.2/gcc_64/mkspecs/modules/qt_lib_quickdialogs2quickimpl.pri:
../../6.6.2/gcc_64/mkspecs/modules/qt_lib_quickdialogs2quickimpl_private.pri:
../../6.6.2/gcc_64/mkspecs/modules/qt_lib_quickdialogs2utils.pri:
../../6.6.2/gcc_64/mkspecs/modules/qt_lib_quickdialogs2utils_private.pri:
../../6.6.2/gcc_64/mkspecs/modules/qt_lib_quickeffects_private.pri:
../../6.6.2/gcc_64/mkspecs/modules/qt_lib_quicklayouts.pri:
../../6.6.2/gcc_64/mkspecs/modules/qt_lib_quicklayouts_private.pri:
../../6.6.2/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../6.6.2/gcc_64/mkspecs/modules/qt_lib_quickshapes_private.pri:
../../6.6.2/gcc_64/mkspecs/modules/qt_lib_quicktemplates2.pri:
../../6.6.2/gcc_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
../../6.6.2/gcc_64/mkspecs/modules/qt_lib_quicktestutilsprivate_private.pri:
../../6.6.2/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri:
../../6.6.2/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../6.6.2/gcc_64/mkspecs/modules/qt_lib_sql.pri:
../../6.6.2/gcc_64/mkspecs/modules/qt_lib_sql_private.pri:
../../6.6.2/gcc_64/mkspecs/modules/qt_lib_svg.pri:
../../6.6.2/gcc_64/mkspecs/modules/qt_lib_svg_private.pri:
../../6.6.2/gcc_64/mkspecs/modules/qt_lib_svgwidgets.pri:
../../6.6.2/gcc_64/mkspecs/modules/qt_lib_svgwidgets_private.pri:
../../6.6.2/gcc_64/mkspecs/modules/qt_lib_testlib.pri:
../../6.6.2/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri:
../../6.6.2/gcc_64/mkspecs/modules/qt_lib_tools_private.pri:
../../6.6.2/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri:
../../6.6.2/gcc_64/mkspecs/modules/qt_lib_uitools.pri:
../../6.6.2/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri:
../../6.6.2/gcc_64/mkspecs/modules/qt_lib_wayland_egl_client_hw_integration_private.pri:
../../6.6.2/gcc_64/mkspecs/modules/qt_lib_waylandclient.pri:
../../6.6.2/gcc_64/mkspecs/modules/qt_lib_waylandclient_private.pri:
../../6.6.2/gcc_64/mkspecs/modules/qt_lib_waylandglobal_private.pri:
../../6.6.2/gcc_64/mkspecs/modules/qt_lib_widgets.pri:
../../6.6.2/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri:
../../6.6.2/gcc_64/mkspecs/modules/qt_lib_wl_shell_integration_private.pri:
../../6.6.2/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
../../6.6.2/gcc_64/mkspecs/modules/qt_lib_xml.pri:
../../6.6.2/gcc_64/mkspecs/modules/qt_lib_xml_private.pri:
../../6.6.2/gcc_64/mkspecs/features/qt_functions.prf:
../../6.6.2/gcc_64/mkspecs/features/qt_config.prf:
../../6.6.2/gcc_64/mkspecs/linux-clang/qmake.conf:
../../6.6.2/gcc_64/mkspecs/features/spec_post.prf:
.qmake.stash:
../../6.6.2/gcc_64/mkspecs/features/exclusive_builds.prf:
../../6.6.2/gcc_64/mkspecs/features/toolchain.prf:
../../6.6.2/gcc_64/mkspecs/features/default_pre.prf:
../../6.6.2/gcc_64/mkspecs/features/resolve_config.prf:
../../6.6.2/gcc_64/mkspecs/features/default_post.prf:
../../6.6.2/gcc_64/mkspecs/features/cmdline.prf:
../../6.6.2/gcc_64/mkspecs/features/qtquickcompiler.prf:
../../6.6.2/gcc_64/mkspecs/features/warn_on.prf:
../../6.6.2/gcc_64/mkspecs/features/permissions.prf:
../../6.6.2/gcc_64/mkspecs/features/qt.prf:
../../6.6.2/gcc_64/mkspecs/features/resources_functions.prf:
../../6.6.2/gcc_64/mkspecs/features/resources.prf:
../../6.6.2/gcc_64/mkspecs/features/moc.prf:
../../6.6.2/gcc_64/mkspecs/features/unix/thread.prf:
../../6.6.2/gcc_64/mkspecs/features/qmake_use.prf:
../../6.6.2/gcc_64/mkspecs/features/file_copies.prf:
../../6.6.2/gcc_64/mkspecs/features/testcase_targets.prf:
../../6.6.2/gcc_64/mkspecs/features/exceptions.prf:
../../6.6.2/gcc_64/mkspecs/features/yacc.prf:
../../6.6.2/gcc_64/mkspecs/features/lex.prf:
server.pro:
../../6.6.2/gcc_64/lib/libQt6Network.prl:
../../6.6.2/gcc_64/lib/libQt6Sql.prl:
../../6.6.2/gcc_64/lib/libQt6Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile server.pro -spec linux-clang CONFIG+=qtquickcompiler

qmake_all: FORCE


all: Makefile server

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents ../../6.6.2/gcc_64/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents db_connection.h server.h $(DISTDIR)/
	$(COPY_FILE) --parents db_connection.cpp main.cpp server.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: ../../6.6.2/gcc_64/mkspecs/features/data/dummy.cpp
	clang++ -pipe -O2 -std=gnu++1z -Wall -Wextra -fPIC -dM -E -o moc_predefs.h ../../6.6.2/gcc_64/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_server.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_server.cpp
moc_server.cpp: server.h \
		../../6.6.2/gcc_64/include/QtNetwork/QTcpServer \
		../../6.6.2/gcc_64/include/QtNetwork/qtcpserver.h \
		../../6.6.2/gcc_64/include/QtNetwork/qtnetworkglobal.h \
		../../6.6.2/gcc_64/include/QtCore/qglobal.h \
		../../6.6.2/gcc_64/include/QtCore/qtversionchecks.h \
		../../6.6.2/gcc_64/include/QtCore/qtconfiginclude.h \
		../../6.6.2/gcc_64/include/QtCore/qconfig.h \
		../../6.6.2/gcc_64/include/QtCore/qtcore-config.h \
		../../6.6.2/gcc_64/include/QtCore/qtconfigmacros.h \
		../../6.6.2/gcc_64/include/QtCore/qtcoreexports.h \
		../../6.6.2/gcc_64/include/QtCore/qcompilerdetection.h \
		../../6.6.2/gcc_64/include/QtCore/qsystemdetection.h \
		../../6.6.2/gcc_64/include/QtCore/qprocessordetection.h \
		../../6.6.2/gcc_64/include/QtCore/qtdeprecationmarkers.h \
		../../6.6.2/gcc_64/include/QtCore/qtpreprocessorsupport.h \
		../../6.6.2/gcc_64/include/QtCore/qassert.h \
		../../6.6.2/gcc_64/include/QtCore/qtnoop.h \
		../../6.6.2/gcc_64/include/QtCore/qtypes.h \
		../../6.6.2/gcc_64/include/QtCore/qtversion.h \
		../../6.6.2/gcc_64/include/QtCore/qtclasshelpermacros.h \
		../../6.6.2/gcc_64/include/QtCore/qtypeinfo.h \
		../../6.6.2/gcc_64/include/QtCore/qcontainerfwd.h \
		../../6.6.2/gcc_64/include/QtCore/qsysinfo.h \
		../../6.6.2/gcc_64/include/QtCore/qlogging.h \
		../../6.6.2/gcc_64/include/QtCore/qflags.h \
		../../6.6.2/gcc_64/include/QtCore/qcompare_impl.h \
		../../6.6.2/gcc_64/include/QtCore/qatomic.h \
		../../6.6.2/gcc_64/include/QtCore/qbasicatomic.h \
		../../6.6.2/gcc_64/include/QtCore/qatomic_cxx11.h \
		../../6.6.2/gcc_64/include/QtCore/qgenericatomic.h \
		../../6.6.2/gcc_64/include/QtCore/qconstructormacros.h \
		../../6.6.2/gcc_64/include/QtCore/qdarwinhelpers.h \
		../../6.6.2/gcc_64/include/QtCore/qexceptionhandling.h \
		../../6.6.2/gcc_64/include/QtCore/qforeach.h \
		../../6.6.2/gcc_64/include/QtCore/qttypetraits.h \
		../../6.6.2/gcc_64/include/QtCore/qfunctionpointer.h \
		../../6.6.2/gcc_64/include/QtCore/qglobalstatic.h \
		../../6.6.2/gcc_64/include/QtCore/qmalloc.h \
		../../6.6.2/gcc_64/include/QtCore/qminmax.h \
		../../6.6.2/gcc_64/include/QtCore/qnumeric.h \
		../../6.6.2/gcc_64/include/QtCore/qoverload.h \
		../../6.6.2/gcc_64/include/QtCore/qswap.h \
		../../6.6.2/gcc_64/include/QtCore/qtenvironmentvariables.h \
		../../6.6.2/gcc_64/include/QtCore/qtresource.h \
		../../6.6.2/gcc_64/include/QtCore/qttranslation.h \
		../../6.6.2/gcc_64/include/QtCore/qversiontagging.h \
		../../6.6.2/gcc_64/include/QtNetwork/qtnetwork-config.h \
		../../6.6.2/gcc_64/include/QtNetwork/qtnetworkexports.h \
		../../6.6.2/gcc_64/include/QtCore/qobject.h \
		../../6.6.2/gcc_64/include/QtCore/qobjectdefs.h \
		../../6.6.2/gcc_64/include/QtCore/qnamespace.h \
		../../6.6.2/gcc_64/include/QtCore/qtmetamacros.h \
		../../6.6.2/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../../6.6.2/gcc_64/include/QtCore/qfunctionaltools_impl.h \
		../../6.6.2/gcc_64/include/QtCore/qstring.h \
		../../6.6.2/gcc_64/include/QtCore/qchar.h \
		../../6.6.2/gcc_64/include/QtCore/qstringview.h \
		../../6.6.2/gcc_64/include/QtCore/qbytearray.h \
		../../6.6.2/gcc_64/include/QtCore/qrefcount.h \
		../../6.6.2/gcc_64/include/QtCore/qarraydata.h \
		../../6.6.2/gcc_64/include/QtCore/qpair.h \
		../../6.6.2/gcc_64/include/QtCore/qarraydatapointer.h \
		../../6.6.2/gcc_64/include/QtCore/qarraydataops.h \
		../../6.6.2/gcc_64/include/QtCore/qcontainertools_impl.h \
		../../6.6.2/gcc_64/include/QtCore/qxptype_traits.h \
		../../6.6.2/gcc_64/include/QtCore/q20functional.h \
		../../6.6.2/gcc_64/include/QtCore/q20memory.h \
		../../6.6.2/gcc_64/include/QtCore/qbytearrayalgorithms.h \
		../../6.6.2/gcc_64/include/QtCore/qbytearrayview.h \
		../../6.6.2/gcc_64/include/QtCore/qstringfwd.h \
		../../6.6.2/gcc_64/include/QtCore/q20type_traits.h \
		../../6.6.2/gcc_64/include/QtCore/qstringliteral.h \
		../../6.6.2/gcc_64/include/QtCore/qstringalgorithms.h \
		../../6.6.2/gcc_64/include/QtCore/qlatin1stringview.h \
		../../6.6.2/gcc_64/include/QtCore/qanystringview.h \
		../../6.6.2/gcc_64/include/QtCore/qutf8stringview.h \
		../../6.6.2/gcc_64/include/QtCore/qstringtokenizer.h \
		../../6.6.2/gcc_64/include/QtCore/qstringbuilder.h \
		../../6.6.2/gcc_64/include/QtCore/qlist.h \
		../../6.6.2/gcc_64/include/QtCore/qhashfunctions.h \
		../../6.6.2/gcc_64/include/QtCore/qiterator.h \
		../../6.6.2/gcc_64/include/QtCore/qbytearraylist.h \
		../../6.6.2/gcc_64/include/QtCore/qstringlist.h \
		../../6.6.2/gcc_64/include/QtCore/qalgorithms.h \
		../../6.6.2/gcc_64/include/QtCore/qstringmatcher.h \
		../../6.6.2/gcc_64/include/QtCore/qcoreevent.h \
		../../6.6.2/gcc_64/include/QtCore/qscopedpointer.h \
		../../6.6.2/gcc_64/include/QtCore/qmetatype.h \
		../../6.6.2/gcc_64/include/QtCore/qcompare.h \
		../../6.6.2/gcc_64/include/QtCore/qdatastream.h \
		../../6.6.2/gcc_64/include/QtCore/qiodevicebase.h \
		../../6.6.2/gcc_64/include/QtCore/qfloat16.h \
		../../6.6.2/gcc_64/include/QtCore/qmath.h \
		../../6.6.2/gcc_64/include/QtCore/qiterable.h \
		../../6.6.2/gcc_64/include/QtCore/qmetacontainer.h \
		../../6.6.2/gcc_64/include/QtCore/qcontainerinfo.h \
		../../6.6.2/gcc_64/include/QtCore/qtaggedpointer.h \
		../../6.6.2/gcc_64/include/QtCore/qscopeguard.h \
		../../6.6.2/gcc_64/include/QtCore/qobject_impl.h \
		../../6.6.2/gcc_64/include/QtCore/qbindingstorage.h \
		../../6.6.2/gcc_64/include/QtNetwork/qabstractsocket.h \
		../../6.6.2/gcc_64/include/QtNetwork/qhostaddress.h \
		../../6.6.2/gcc_64/include/QtCore/qshareddata.h \
		../../6.6.2/gcc_64/include/QtCore/qiodevice.h \
		../../6.6.2/gcc_64/include/QtCore/qdebug.h \
		../../6.6.2/gcc_64/include/QtCore/qtextstream.h \
		../../6.6.2/gcc_64/include/QtCore/qstringconverter_base.h \
		../../6.6.2/gcc_64/include/QtCore/qcontiguouscache.h \
		../../6.6.2/gcc_64/include/QtCore/qsharedpointer.h \
		../../6.6.2/gcc_64/include/QtCore/qsharedpointer_impl.h \
		../../6.6.2/gcc_64/include/QtCore/qmap.h \
		../../6.6.2/gcc_64/include/QtCore/qshareddata_impl.h \
		../../6.6.2/gcc_64/include/QtCore/qset.h \
		../../6.6.2/gcc_64/include/QtCore/qhash.h \
		../../6.6.2/gcc_64/include/QtCore/qvarlengtharray.h \
		../../6.6.2/gcc_64/include/QtNetwork/QTcpSocket \
		../../6.6.2/gcc_64/include/QtNetwork/qtcpsocket.h \
		../../6.6.2/gcc_64/include/QtCore/qvariant.h \
		../../6.6.2/gcc_64/include/QtCore/q23utility.h \
		../../6.6.2/gcc_64/include/QtCore/QVector \
		../../6.6.2/gcc_64/include/QtCore/qvector.h \
		../../6.6.2/gcc_64/include/QtCore/QTime \
		../../6.6.2/gcc_64/include/QtCore/qdatetime.h \
		../../6.6.2/gcc_64/include/QtCore/qcalendar.h \
		../../6.6.2/gcc_64/include/QtCore/qlocale.h \
		../../6.6.2/gcc_64/include/QtCore/QString \
		../../6.6.2/gcc_64/include/QtCore/QDataStream \
		../../6.6.2/gcc_64/include/QtCore/QMap \
		db_connection.h \
		../../6.6.2/gcc_64/include/QtSql/QSqlDatabase \
		../../6.6.2/gcc_64/include/QtSql/qsqldatabase.h \
		../../6.6.2/gcc_64/include/QtSql/qtsqlglobal.h \
		../../6.6.2/gcc_64/include/QtSql/qtsql-config.h \
		../../6.6.2/gcc_64/include/QtSql/qtsqlexports.h \
		../../6.6.2/gcc_64/include/QtCore/QDebug \
		../../6.6.2/gcc_64/include/QtCore/QCryptographicHash \
		../../6.6.2/gcc_64/include/QtCore/qcryptographichash.h \
		../../6.6.2/gcc_64/include/QtSql/QSqlQuery \
		../../6.6.2/gcc_64/include/QtSql/qsqlquery.h \
		../../6.6.2/gcc_64/include/QtCore/QByteArray \
		../../6.6.2/gcc_64/include/QtSql/QSqlError \
		../../6.6.2/gcc_64/include/QtSql/qsqlerror.h \
		../../6.6.2/gcc_64/include/QtCore/QJsonArray \
		../../6.6.2/gcc_64/include/QtCore/qjsonarray.h \
		../../6.6.2/gcc_64/include/QtCore/qjsonvalue.h \
		../../6.6.2/gcc_64/include/QtCore/qcborvalue.h \
		../../6.6.2/gcc_64/include/QtCore/qcborcommon.h \
		../../6.6.2/gcc_64/include/QtCore/qregularexpression.h \
		../../6.6.2/gcc_64/include/QtCore/qurl.h \
		../../6.6.2/gcc_64/include/QtCore/quuid.h \
		../../6.6.2/gcc_64/include/QtCore/qendian.h \
		../../6.6.2/gcc_64/include/QtCore/QJsonDocument \
		../../6.6.2/gcc_64/include/QtCore/qjsondocument.h \
		../../6.6.2/gcc_64/include/QtCore/QJsonObject \
		../../6.6.2/gcc_64/include/QtCore/qjsonobject.h \
		moc_predefs.h \
		../../6.6.2/gcc_64/libexec/moc
	/home/kali/Qt/6.6.2/gcc_64/libexec/moc $(DEFINES) --include /home/kali/Qt/projects/server/moc_predefs.h -I/home/kali/Qt/6.6.2/gcc_64/mkspecs/linux-clang -I/home/kali/Qt/projects/server -I/home/kali/Qt/6.6.2/gcc_64/include -I/home/kali/Qt/6.6.2/gcc_64/include/QtNetwork -I/home/kali/Qt/6.6.2/gcc_64/include/QtSql -I/home/kali/Qt/6.6.2/gcc_64/include/QtCore -I/usr/include/c++/13 -I/usr/include/x86_64-linux-gnu/c++/13 -I/usr/include/c++/13/backward -I/usr/lib/llvm-16/lib/clang/16/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include server.h -o moc_server.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean compiler_moc_header_clean 

####### Compile

db_connection.o: db_connection.cpp db_connection.h \
		../../6.6.2/gcc_64/include/QtSql/QSqlDatabase \
		../../6.6.2/gcc_64/include/QtSql/qsqldatabase.h \
		../../6.6.2/gcc_64/include/QtSql/qtsqlglobal.h \
		../../6.6.2/gcc_64/include/QtCore/qglobal.h \
		../../6.6.2/gcc_64/include/QtCore/qtversionchecks.h \
		../../6.6.2/gcc_64/include/QtCore/qtconfiginclude.h \
		../../6.6.2/gcc_64/include/QtCore/qconfig.h \
		../../6.6.2/gcc_64/include/QtCore/qtcore-config.h \
		../../6.6.2/gcc_64/include/QtCore/qtconfigmacros.h \
		../../6.6.2/gcc_64/include/QtCore/qtcoreexports.h \
		../../6.6.2/gcc_64/include/QtCore/qcompilerdetection.h \
		../../6.6.2/gcc_64/include/QtCore/qsystemdetection.h \
		../../6.6.2/gcc_64/include/QtCore/qprocessordetection.h \
		../../6.6.2/gcc_64/include/QtCore/qtdeprecationmarkers.h \
		../../6.6.2/gcc_64/include/QtCore/qtpreprocessorsupport.h \
		../../6.6.2/gcc_64/include/QtCore/qassert.h \
		../../6.6.2/gcc_64/include/QtCore/qtnoop.h \
		../../6.6.2/gcc_64/include/QtCore/qtypes.h \
		../../6.6.2/gcc_64/include/QtCore/qtversion.h \
		../../6.6.2/gcc_64/include/QtCore/qtclasshelpermacros.h \
		../../6.6.2/gcc_64/include/QtCore/qtypeinfo.h \
		../../6.6.2/gcc_64/include/QtCore/qcontainerfwd.h \
		../../6.6.2/gcc_64/include/QtCore/qsysinfo.h \
		../../6.6.2/gcc_64/include/QtCore/qlogging.h \
		../../6.6.2/gcc_64/include/QtCore/qflags.h \
		../../6.6.2/gcc_64/include/QtCore/qcompare_impl.h \
		../../6.6.2/gcc_64/include/QtCore/qatomic.h \
		../../6.6.2/gcc_64/include/QtCore/qbasicatomic.h \
		../../6.6.2/gcc_64/include/QtCore/qatomic_cxx11.h \
		../../6.6.2/gcc_64/include/QtCore/qgenericatomic.h \
		../../6.6.2/gcc_64/include/QtCore/qconstructormacros.h \
		../../6.6.2/gcc_64/include/QtCore/qdarwinhelpers.h \
		../../6.6.2/gcc_64/include/QtCore/qexceptionhandling.h \
		../../6.6.2/gcc_64/include/QtCore/qforeach.h \
		../../6.6.2/gcc_64/include/QtCore/qttypetraits.h \
		../../6.6.2/gcc_64/include/QtCore/qfunctionpointer.h \
		../../6.6.2/gcc_64/include/QtCore/qglobalstatic.h \
		../../6.6.2/gcc_64/include/QtCore/qmalloc.h \
		../../6.6.2/gcc_64/include/QtCore/qminmax.h \
		../../6.6.2/gcc_64/include/QtCore/qnumeric.h \
		../../6.6.2/gcc_64/include/QtCore/qoverload.h \
		../../6.6.2/gcc_64/include/QtCore/qswap.h \
		../../6.6.2/gcc_64/include/QtCore/qtenvironmentvariables.h \
		../../6.6.2/gcc_64/include/QtCore/qtresource.h \
		../../6.6.2/gcc_64/include/QtCore/qttranslation.h \
		../../6.6.2/gcc_64/include/QtCore/qversiontagging.h \
		../../6.6.2/gcc_64/include/QtSql/qtsql-config.h \
		../../6.6.2/gcc_64/include/QtSql/qtsqlexports.h \
		../../6.6.2/gcc_64/include/QtCore/qstring.h \
		../../6.6.2/gcc_64/include/QtCore/qchar.h \
		../../6.6.2/gcc_64/include/QtCore/qstringview.h \
		../../6.6.2/gcc_64/include/QtCore/qbytearray.h \
		../../6.6.2/gcc_64/include/QtCore/qrefcount.h \
		../../6.6.2/gcc_64/include/QtCore/qnamespace.h \
		../../6.6.2/gcc_64/include/QtCore/qtmetamacros.h \
		../../6.6.2/gcc_64/include/QtCore/qarraydata.h \
		../../6.6.2/gcc_64/include/QtCore/qpair.h \
		../../6.6.2/gcc_64/include/QtCore/qarraydatapointer.h \
		../../6.6.2/gcc_64/include/QtCore/qarraydataops.h \
		../../6.6.2/gcc_64/include/QtCore/qcontainertools_impl.h \
		../../6.6.2/gcc_64/include/QtCore/qxptype_traits.h \
		../../6.6.2/gcc_64/include/QtCore/q20functional.h \
		../../6.6.2/gcc_64/include/QtCore/q20memory.h \
		../../6.6.2/gcc_64/include/QtCore/qbytearrayalgorithms.h \
		../../6.6.2/gcc_64/include/QtCore/qbytearrayview.h \
		../../6.6.2/gcc_64/include/QtCore/qstringfwd.h \
		../../6.6.2/gcc_64/include/QtCore/q20type_traits.h \
		../../6.6.2/gcc_64/include/QtCore/qstringliteral.h \
		../../6.6.2/gcc_64/include/QtCore/qstringalgorithms.h \
		../../6.6.2/gcc_64/include/QtCore/qlatin1stringview.h \
		../../6.6.2/gcc_64/include/QtCore/qanystringview.h \
		../../6.6.2/gcc_64/include/QtCore/qutf8stringview.h \
		../../6.6.2/gcc_64/include/QtCore/qstringtokenizer.h \
		../../6.6.2/gcc_64/include/QtCore/qstringbuilder.h \
		../../6.6.2/gcc_64/include/QtCore/QDebug \
		../../6.6.2/gcc_64/include/QtCore/qdebug.h \
		../../6.6.2/gcc_64/include/QtCore/qtextstream.h \
		../../6.6.2/gcc_64/include/QtCore/qiodevicebase.h \
		../../6.6.2/gcc_64/include/QtCore/qscopedpointer.h \
		../../6.6.2/gcc_64/include/QtCore/qstringconverter_base.h \
		../../6.6.2/gcc_64/include/QtCore/qcontiguouscache.h \
		../../6.6.2/gcc_64/include/QtCore/qsharedpointer.h \
		../../6.6.2/gcc_64/include/QtCore/qshareddata.h \
		../../6.6.2/gcc_64/include/QtCore/qhashfunctions.h \
		../../6.6.2/gcc_64/include/QtCore/qsharedpointer_impl.h \
		../../6.6.2/gcc_64/include/QtCore/qmetatype.h \
		../../6.6.2/gcc_64/include/QtCore/qcompare.h \
		../../6.6.2/gcc_64/include/QtCore/qdatastream.h \
		../../6.6.2/gcc_64/include/QtCore/qfloat16.h \
		../../6.6.2/gcc_64/include/QtCore/qmath.h \
		../../6.6.2/gcc_64/include/QtCore/qalgorithms.h \
		../../6.6.2/gcc_64/include/QtCore/qiterable.h \
		../../6.6.2/gcc_64/include/QtCore/qmetacontainer.h \
		../../6.6.2/gcc_64/include/QtCore/qcontainerinfo.h \
		../../6.6.2/gcc_64/include/QtCore/qtaggedpointer.h \
		../../6.6.2/gcc_64/include/QtCore/qobjectdefs.h \
		../../6.6.2/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../../6.6.2/gcc_64/include/QtCore/qfunctionaltools_impl.h \
		../../6.6.2/gcc_64/include/QtCore/qscopeguard.h \
		../../6.6.2/gcc_64/include/QtCore/qlist.h \
		../../6.6.2/gcc_64/include/QtCore/qiterator.h \
		../../6.6.2/gcc_64/include/QtCore/qbytearraylist.h \
		../../6.6.2/gcc_64/include/QtCore/qstringlist.h \
		../../6.6.2/gcc_64/include/QtCore/qstringmatcher.h \
		../../6.6.2/gcc_64/include/QtCore/qmap.h \
		../../6.6.2/gcc_64/include/QtCore/qshareddata_impl.h \
		../../6.6.2/gcc_64/include/QtCore/qset.h \
		../../6.6.2/gcc_64/include/QtCore/qhash.h \
		../../6.6.2/gcc_64/include/QtCore/qvarlengtharray.h \
		../../6.6.2/gcc_64/include/QtCore/QCryptographicHash \
		../../6.6.2/gcc_64/include/QtCore/qcryptographichash.h \
		../../6.6.2/gcc_64/include/QtSql/QSqlQuery \
		../../6.6.2/gcc_64/include/QtSql/qsqlquery.h \
		../../6.6.2/gcc_64/include/QtCore/qvariant.h \
		../../6.6.2/gcc_64/include/QtCore/q23utility.h \
		../../6.6.2/gcc_64/include/QtCore/qobject.h \
		../../6.6.2/gcc_64/include/QtCore/qcoreevent.h \
		../../6.6.2/gcc_64/include/QtCore/qobject_impl.h \
		../../6.6.2/gcc_64/include/QtCore/qbindingstorage.h \
		../../6.6.2/gcc_64/include/QtCore/QByteArray \
		../../6.6.2/gcc_64/include/QtSql/QSqlError \
		../../6.6.2/gcc_64/include/QtSql/qsqlerror.h \
		../../6.6.2/gcc_64/include/QtCore/QJsonArray \
		../../6.6.2/gcc_64/include/QtCore/qjsonarray.h \
		../../6.6.2/gcc_64/include/QtCore/qjsonvalue.h \
		../../6.6.2/gcc_64/include/QtCore/qcborvalue.h \
		../../6.6.2/gcc_64/include/QtCore/qdatetime.h \
		../../6.6.2/gcc_64/include/QtCore/qcalendar.h \
		../../6.6.2/gcc_64/include/QtCore/qlocale.h \
		../../6.6.2/gcc_64/include/QtCore/qcborcommon.h \
		../../6.6.2/gcc_64/include/QtCore/qregularexpression.h \
		../../6.6.2/gcc_64/include/QtCore/qurl.h \
		../../6.6.2/gcc_64/include/QtCore/quuid.h \
		../../6.6.2/gcc_64/include/QtCore/qendian.h \
		../../6.6.2/gcc_64/include/QtCore/QJsonDocument \
		../../6.6.2/gcc_64/include/QtCore/qjsondocument.h \
		../../6.6.2/gcc_64/include/QtCore/QJsonObject \
		../../6.6.2/gcc_64/include/QtCore/qjsonobject.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o db_connection.o db_connection.cpp

main.o: main.cpp ../../6.6.2/gcc_64/include/QtCore/QCoreApplication \
		../../6.6.2/gcc_64/include/QtCore/qcoreapplication.h \
		../../6.6.2/gcc_64/include/QtCore/qglobal.h \
		../../6.6.2/gcc_64/include/QtCore/qtversionchecks.h \
		../../6.6.2/gcc_64/include/QtCore/qtconfiginclude.h \
		../../6.6.2/gcc_64/include/QtCore/qconfig.h \
		../../6.6.2/gcc_64/include/QtCore/qtcore-config.h \
		../../6.6.2/gcc_64/include/QtCore/qtconfigmacros.h \
		../../6.6.2/gcc_64/include/QtCore/qtcoreexports.h \
		../../6.6.2/gcc_64/include/QtCore/qcompilerdetection.h \
		../../6.6.2/gcc_64/include/QtCore/qsystemdetection.h \
		../../6.6.2/gcc_64/include/QtCore/qprocessordetection.h \
		../../6.6.2/gcc_64/include/QtCore/qtdeprecationmarkers.h \
		../../6.6.2/gcc_64/include/QtCore/qtpreprocessorsupport.h \
		../../6.6.2/gcc_64/include/QtCore/qassert.h \
		../../6.6.2/gcc_64/include/QtCore/qtnoop.h \
		../../6.6.2/gcc_64/include/QtCore/qtypes.h \
		../../6.6.2/gcc_64/include/QtCore/qtversion.h \
		../../6.6.2/gcc_64/include/QtCore/qtclasshelpermacros.h \
		../../6.6.2/gcc_64/include/QtCore/qtypeinfo.h \
		../../6.6.2/gcc_64/include/QtCore/qcontainerfwd.h \
		../../6.6.2/gcc_64/include/QtCore/qsysinfo.h \
		../../6.6.2/gcc_64/include/QtCore/qlogging.h \
		../../6.6.2/gcc_64/include/QtCore/qflags.h \
		../../6.6.2/gcc_64/include/QtCore/qcompare_impl.h \
		../../6.6.2/gcc_64/include/QtCore/qatomic.h \
		../../6.6.2/gcc_64/include/QtCore/qbasicatomic.h \
		../../6.6.2/gcc_64/include/QtCore/qatomic_cxx11.h \
		../../6.6.2/gcc_64/include/QtCore/qgenericatomic.h \
		../../6.6.2/gcc_64/include/QtCore/qconstructormacros.h \
		../../6.6.2/gcc_64/include/QtCore/qdarwinhelpers.h \
		../../6.6.2/gcc_64/include/QtCore/qexceptionhandling.h \
		../../6.6.2/gcc_64/include/QtCore/qforeach.h \
		../../6.6.2/gcc_64/include/QtCore/qttypetraits.h \
		../../6.6.2/gcc_64/include/QtCore/qfunctionpointer.h \
		../../6.6.2/gcc_64/include/QtCore/qglobalstatic.h \
		../../6.6.2/gcc_64/include/QtCore/qmalloc.h \
		../../6.6.2/gcc_64/include/QtCore/qminmax.h \
		../../6.6.2/gcc_64/include/QtCore/qnumeric.h \
		../../6.6.2/gcc_64/include/QtCore/qoverload.h \
		../../6.6.2/gcc_64/include/QtCore/qswap.h \
		../../6.6.2/gcc_64/include/QtCore/qtenvironmentvariables.h \
		../../6.6.2/gcc_64/include/QtCore/qtresource.h \
		../../6.6.2/gcc_64/include/QtCore/qttranslation.h \
		../../6.6.2/gcc_64/include/QtCore/qversiontagging.h \
		../../6.6.2/gcc_64/include/QtCore/qstring.h \
		../../6.6.2/gcc_64/include/QtCore/qchar.h \
		../../6.6.2/gcc_64/include/QtCore/qstringview.h \
		../../6.6.2/gcc_64/include/QtCore/qbytearray.h \
		../../6.6.2/gcc_64/include/QtCore/qrefcount.h \
		../../6.6.2/gcc_64/include/QtCore/qnamespace.h \
		../../6.6.2/gcc_64/include/QtCore/qtmetamacros.h \
		../../6.6.2/gcc_64/include/QtCore/qarraydata.h \
		../../6.6.2/gcc_64/include/QtCore/qpair.h \
		../../6.6.2/gcc_64/include/QtCore/qarraydatapointer.h \
		../../6.6.2/gcc_64/include/QtCore/qarraydataops.h \
		../../6.6.2/gcc_64/include/QtCore/qcontainertools_impl.h \
		../../6.6.2/gcc_64/include/QtCore/qxptype_traits.h \
		../../6.6.2/gcc_64/include/QtCore/q20functional.h \
		../../6.6.2/gcc_64/include/QtCore/q20memory.h \
		../../6.6.2/gcc_64/include/QtCore/qbytearrayalgorithms.h \
		../../6.6.2/gcc_64/include/QtCore/qbytearrayview.h \
		../../6.6.2/gcc_64/include/QtCore/qstringfwd.h \
		../../6.6.2/gcc_64/include/QtCore/q20type_traits.h \
		../../6.6.2/gcc_64/include/QtCore/qstringliteral.h \
		../../6.6.2/gcc_64/include/QtCore/qstringalgorithms.h \
		../../6.6.2/gcc_64/include/QtCore/qlatin1stringview.h \
		../../6.6.2/gcc_64/include/QtCore/qanystringview.h \
		../../6.6.2/gcc_64/include/QtCore/qutf8stringview.h \
		../../6.6.2/gcc_64/include/QtCore/qstringtokenizer.h \
		../../6.6.2/gcc_64/include/QtCore/qstringbuilder.h \
		../../6.6.2/gcc_64/include/QtCore/qcoreevent.h \
		../../6.6.2/gcc_64/include/QtCore/qobjectdefs.h \
		../../6.6.2/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../../6.6.2/gcc_64/include/QtCore/qfunctionaltools_impl.h \
		../../6.6.2/gcc_64/include/QtCore/qeventloop.h \
		../../6.6.2/gcc_64/include/QtCore/qobject.h \
		../../6.6.2/gcc_64/include/QtCore/qlist.h \
		../../6.6.2/gcc_64/include/QtCore/qhashfunctions.h \
		../../6.6.2/gcc_64/include/QtCore/qiterator.h \
		../../6.6.2/gcc_64/include/QtCore/qbytearraylist.h \
		../../6.6.2/gcc_64/include/QtCore/qstringlist.h \
		../../6.6.2/gcc_64/include/QtCore/qalgorithms.h \
		../../6.6.2/gcc_64/include/QtCore/qstringmatcher.h \
		../../6.6.2/gcc_64/include/QtCore/qscopedpointer.h \
		../../6.6.2/gcc_64/include/QtCore/qmetatype.h \
		../../6.6.2/gcc_64/include/QtCore/qcompare.h \
		../../6.6.2/gcc_64/include/QtCore/qdatastream.h \
		../../6.6.2/gcc_64/include/QtCore/qiodevicebase.h \
		../../6.6.2/gcc_64/include/QtCore/qfloat16.h \
		../../6.6.2/gcc_64/include/QtCore/qmath.h \
		../../6.6.2/gcc_64/include/QtCore/qiterable.h \
		../../6.6.2/gcc_64/include/QtCore/qmetacontainer.h \
		../../6.6.2/gcc_64/include/QtCore/qcontainerinfo.h \
		../../6.6.2/gcc_64/include/QtCore/qtaggedpointer.h \
		../../6.6.2/gcc_64/include/QtCore/qscopeguard.h \
		../../6.6.2/gcc_64/include/QtCore/qobject_impl.h \
		../../6.6.2/gcc_64/include/QtCore/qbindingstorage.h \
		../../6.6.2/gcc_64/include/QtCore/qnativeinterface.h \
		../../6.6.2/gcc_64/include/QtCore/qdebug.h \
		../../6.6.2/gcc_64/include/QtCore/qtextstream.h \
		../../6.6.2/gcc_64/include/QtCore/qstringconverter_base.h \
		../../6.6.2/gcc_64/include/QtCore/qcontiguouscache.h \
		../../6.6.2/gcc_64/include/QtCore/qsharedpointer.h \
		../../6.6.2/gcc_64/include/QtCore/qshareddata.h \
		../../6.6.2/gcc_64/include/QtCore/qsharedpointer_impl.h \
		../../6.6.2/gcc_64/include/QtCore/qmap.h \
		../../6.6.2/gcc_64/include/QtCore/qshareddata_impl.h \
		../../6.6.2/gcc_64/include/QtCore/qset.h \
		../../6.6.2/gcc_64/include/QtCore/qhash.h \
		../../6.6.2/gcc_64/include/QtCore/qvarlengtharray.h \
		../../6.6.2/gcc_64/include/QtCore/qcoreapplication_platform.h \
		../../6.6.2/gcc_64/include/QtCore/qfuture.h \
		../../6.6.2/gcc_64/include/QtCore/qfutureinterface.h \
		../../6.6.2/gcc_64/include/QtCore/qmutex.h \
		../../6.6.2/gcc_64/include/QtCore/qdeadlinetimer.h \
		../../6.6.2/gcc_64/include/QtCore/qelapsedtimer.h \
		../../6.6.2/gcc_64/include/QtCore/qtsan_impl.h \
		../../6.6.2/gcc_64/include/QtCore/qresultstore.h \
		../../6.6.2/gcc_64/include/QtCore/qfuture_impl.h \
		../../6.6.2/gcc_64/include/QtCore/qthreadpool.h \
		../../6.6.2/gcc_64/include/QtCore/qthread.h \
		../../6.6.2/gcc_64/include/QtCore/qrunnable.h \
		../../6.6.2/gcc_64/include/QtCore/qexception.h \
		../../6.6.2/gcc_64/include/QtCore/qpointer.h \
		../../6.6.2/gcc_64/include/QtCore/qpromise.h \
		../../6.6.2/gcc_64/include/QtCore/qvariant.h \
		../../6.6.2/gcc_64/include/QtCore/q23utility.h \
		server.h \
		../../6.6.2/gcc_64/include/QtNetwork/QTcpServer \
		../../6.6.2/gcc_64/include/QtNetwork/qtcpserver.h \
		../../6.6.2/gcc_64/include/QtNetwork/qtnetworkglobal.h \
		../../6.6.2/gcc_64/include/QtNetwork/qtnetwork-config.h \
		../../6.6.2/gcc_64/include/QtNetwork/qtnetworkexports.h \
		../../6.6.2/gcc_64/include/QtNetwork/qabstractsocket.h \
		../../6.6.2/gcc_64/include/QtNetwork/qhostaddress.h \
		../../6.6.2/gcc_64/include/QtCore/qiodevice.h \
		../../6.6.2/gcc_64/include/QtNetwork/QTcpSocket \
		../../6.6.2/gcc_64/include/QtNetwork/qtcpsocket.h \
		../../6.6.2/gcc_64/include/QtCore/QVector \
		../../6.6.2/gcc_64/include/QtCore/qvector.h \
		../../6.6.2/gcc_64/include/QtCore/QTime \
		../../6.6.2/gcc_64/include/QtCore/qdatetime.h \
		../../6.6.2/gcc_64/include/QtCore/qcalendar.h \
		../../6.6.2/gcc_64/include/QtCore/qlocale.h \
		../../6.6.2/gcc_64/include/QtCore/QString \
		../../6.6.2/gcc_64/include/QtCore/QDataStream \
		../../6.6.2/gcc_64/include/QtCore/QMap \
		db_connection.h \
		../../6.6.2/gcc_64/include/QtSql/QSqlDatabase \
		../../6.6.2/gcc_64/include/QtSql/qsqldatabase.h \
		../../6.6.2/gcc_64/include/QtSql/qtsqlglobal.h \
		../../6.6.2/gcc_64/include/QtSql/qtsql-config.h \
		../../6.6.2/gcc_64/include/QtSql/qtsqlexports.h \
		../../6.6.2/gcc_64/include/QtCore/QDebug \
		../../6.6.2/gcc_64/include/QtCore/QCryptographicHash \
		../../6.6.2/gcc_64/include/QtCore/qcryptographichash.h \
		../../6.6.2/gcc_64/include/QtSql/QSqlQuery \
		../../6.6.2/gcc_64/include/QtSql/qsqlquery.h \
		../../6.6.2/gcc_64/include/QtCore/QByteArray \
		../../6.6.2/gcc_64/include/QtSql/QSqlError \
		../../6.6.2/gcc_64/include/QtSql/qsqlerror.h \
		../../6.6.2/gcc_64/include/QtCore/QJsonArray \
		../../6.6.2/gcc_64/include/QtCore/qjsonarray.h \
		../../6.6.2/gcc_64/include/QtCore/qjsonvalue.h \
		../../6.6.2/gcc_64/include/QtCore/qcborvalue.h \
		../../6.6.2/gcc_64/include/QtCore/qcborcommon.h \
		../../6.6.2/gcc_64/include/QtCore/qregularexpression.h \
		../../6.6.2/gcc_64/include/QtCore/qurl.h \
		../../6.6.2/gcc_64/include/QtCore/quuid.h \
		../../6.6.2/gcc_64/include/QtCore/qendian.h \
		../../6.6.2/gcc_64/include/QtCore/QJsonDocument \
		../../6.6.2/gcc_64/include/QtCore/qjsondocument.h \
		../../6.6.2/gcc_64/include/QtCore/QJsonObject \
		../../6.6.2/gcc_64/include/QtCore/qjsonobject.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

server.o: server.cpp server.h \
		../../6.6.2/gcc_64/include/QtNetwork/QTcpServer \
		../../6.6.2/gcc_64/include/QtNetwork/qtcpserver.h \
		../../6.6.2/gcc_64/include/QtNetwork/qtnetworkglobal.h \
		../../6.6.2/gcc_64/include/QtCore/qglobal.h \
		../../6.6.2/gcc_64/include/QtCore/qtversionchecks.h \
		../../6.6.2/gcc_64/include/QtCore/qtconfiginclude.h \
		../../6.6.2/gcc_64/include/QtCore/qconfig.h \
		../../6.6.2/gcc_64/include/QtCore/qtcore-config.h \
		../../6.6.2/gcc_64/include/QtCore/qtconfigmacros.h \
		../../6.6.2/gcc_64/include/QtCore/qtcoreexports.h \
		../../6.6.2/gcc_64/include/QtCore/qcompilerdetection.h \
		../../6.6.2/gcc_64/include/QtCore/qsystemdetection.h \
		../../6.6.2/gcc_64/include/QtCore/qprocessordetection.h \
		../../6.6.2/gcc_64/include/QtCore/qtdeprecationmarkers.h \
		../../6.6.2/gcc_64/include/QtCore/qtpreprocessorsupport.h \
		../../6.6.2/gcc_64/include/QtCore/qassert.h \
		../../6.6.2/gcc_64/include/QtCore/qtnoop.h \
		../../6.6.2/gcc_64/include/QtCore/qtypes.h \
		../../6.6.2/gcc_64/include/QtCore/qtversion.h \
		../../6.6.2/gcc_64/include/QtCore/qtclasshelpermacros.h \
		../../6.6.2/gcc_64/include/QtCore/qtypeinfo.h \
		../../6.6.2/gcc_64/include/QtCore/qcontainerfwd.h \
		../../6.6.2/gcc_64/include/QtCore/qsysinfo.h \
		../../6.6.2/gcc_64/include/QtCore/qlogging.h \
		../../6.6.2/gcc_64/include/QtCore/qflags.h \
		../../6.6.2/gcc_64/include/QtCore/qcompare_impl.h \
		../../6.6.2/gcc_64/include/QtCore/qatomic.h \
		../../6.6.2/gcc_64/include/QtCore/qbasicatomic.h \
		../../6.6.2/gcc_64/include/QtCore/qatomic_cxx11.h \
		../../6.6.2/gcc_64/include/QtCore/qgenericatomic.h \
		../../6.6.2/gcc_64/include/QtCore/qconstructormacros.h \
		../../6.6.2/gcc_64/include/QtCore/qdarwinhelpers.h \
		../../6.6.2/gcc_64/include/QtCore/qexceptionhandling.h \
		../../6.6.2/gcc_64/include/QtCore/qforeach.h \
		../../6.6.2/gcc_64/include/QtCore/qttypetraits.h \
		../../6.6.2/gcc_64/include/QtCore/qfunctionpointer.h \
		../../6.6.2/gcc_64/include/QtCore/qglobalstatic.h \
		../../6.6.2/gcc_64/include/QtCore/qmalloc.h \
		../../6.6.2/gcc_64/include/QtCore/qminmax.h \
		../../6.6.2/gcc_64/include/QtCore/qnumeric.h \
		../../6.6.2/gcc_64/include/QtCore/qoverload.h \
		../../6.6.2/gcc_64/include/QtCore/qswap.h \
		../../6.6.2/gcc_64/include/QtCore/qtenvironmentvariables.h \
		../../6.6.2/gcc_64/include/QtCore/qtresource.h \
		../../6.6.2/gcc_64/include/QtCore/qttranslation.h \
		../../6.6.2/gcc_64/include/QtCore/qversiontagging.h \
		../../6.6.2/gcc_64/include/QtNetwork/qtnetwork-config.h \
		../../6.6.2/gcc_64/include/QtNetwork/qtnetworkexports.h \
		../../6.6.2/gcc_64/include/QtCore/qobject.h \
		../../6.6.2/gcc_64/include/QtCore/qobjectdefs.h \
		../../6.6.2/gcc_64/include/QtCore/qnamespace.h \
		../../6.6.2/gcc_64/include/QtCore/qtmetamacros.h \
		../../6.6.2/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../../6.6.2/gcc_64/include/QtCore/qfunctionaltools_impl.h \
		../../6.6.2/gcc_64/include/QtCore/qstring.h \
		../../6.6.2/gcc_64/include/QtCore/qchar.h \
		../../6.6.2/gcc_64/include/QtCore/qstringview.h \
		../../6.6.2/gcc_64/include/QtCore/qbytearray.h \
		../../6.6.2/gcc_64/include/QtCore/qrefcount.h \
		../../6.6.2/gcc_64/include/QtCore/qarraydata.h \
		../../6.6.2/gcc_64/include/QtCore/qpair.h \
		../../6.6.2/gcc_64/include/QtCore/qarraydatapointer.h \
		../../6.6.2/gcc_64/include/QtCore/qarraydataops.h \
		../../6.6.2/gcc_64/include/QtCore/qcontainertools_impl.h \
		../../6.6.2/gcc_64/include/QtCore/qxptype_traits.h \
		../../6.6.2/gcc_64/include/QtCore/q20functional.h \
		../../6.6.2/gcc_64/include/QtCore/q20memory.h \
		../../6.6.2/gcc_64/include/QtCore/qbytearrayalgorithms.h \
		../../6.6.2/gcc_64/include/QtCore/qbytearrayview.h \
		../../6.6.2/gcc_64/include/QtCore/qstringfwd.h \
		../../6.6.2/gcc_64/include/QtCore/q20type_traits.h \
		../../6.6.2/gcc_64/include/QtCore/qstringliteral.h \
		../../6.6.2/gcc_64/include/QtCore/qstringalgorithms.h \
		../../6.6.2/gcc_64/include/QtCore/qlatin1stringview.h \
		../../6.6.2/gcc_64/include/QtCore/qanystringview.h \
		../../6.6.2/gcc_64/include/QtCore/qutf8stringview.h \
		../../6.6.2/gcc_64/include/QtCore/qstringtokenizer.h \
		../../6.6.2/gcc_64/include/QtCore/qstringbuilder.h \
		../../6.6.2/gcc_64/include/QtCore/qlist.h \
		../../6.6.2/gcc_64/include/QtCore/qhashfunctions.h \
		../../6.6.2/gcc_64/include/QtCore/qiterator.h \
		../../6.6.2/gcc_64/include/QtCore/qbytearraylist.h \
		../../6.6.2/gcc_64/include/QtCore/qstringlist.h \
		../../6.6.2/gcc_64/include/QtCore/qalgorithms.h \
		../../6.6.2/gcc_64/include/QtCore/qstringmatcher.h \
		../../6.6.2/gcc_64/include/QtCore/qcoreevent.h \
		../../6.6.2/gcc_64/include/QtCore/qscopedpointer.h \
		../../6.6.2/gcc_64/include/QtCore/qmetatype.h \
		../../6.6.2/gcc_64/include/QtCore/qcompare.h \
		../../6.6.2/gcc_64/include/QtCore/qdatastream.h \
		../../6.6.2/gcc_64/include/QtCore/qiodevicebase.h \
		../../6.6.2/gcc_64/include/QtCore/qfloat16.h \
		../../6.6.2/gcc_64/include/QtCore/qmath.h \
		../../6.6.2/gcc_64/include/QtCore/qiterable.h \
		../../6.6.2/gcc_64/include/QtCore/qmetacontainer.h \
		../../6.6.2/gcc_64/include/QtCore/qcontainerinfo.h \
		../../6.6.2/gcc_64/include/QtCore/qtaggedpointer.h \
		../../6.6.2/gcc_64/include/QtCore/qscopeguard.h \
		../../6.6.2/gcc_64/include/QtCore/qobject_impl.h \
		../../6.6.2/gcc_64/include/QtCore/qbindingstorage.h \
		../../6.6.2/gcc_64/include/QtNetwork/qabstractsocket.h \
		../../6.6.2/gcc_64/include/QtNetwork/qhostaddress.h \
		../../6.6.2/gcc_64/include/QtCore/qshareddata.h \
		../../6.6.2/gcc_64/include/QtCore/qiodevice.h \
		../../6.6.2/gcc_64/include/QtCore/qdebug.h \
		../../6.6.2/gcc_64/include/QtCore/qtextstream.h \
		../../6.6.2/gcc_64/include/QtCore/qstringconverter_base.h \
		../../6.6.2/gcc_64/include/QtCore/qcontiguouscache.h \
		../../6.6.2/gcc_64/include/QtCore/qsharedpointer.h \
		../../6.6.2/gcc_64/include/QtCore/qsharedpointer_impl.h \
		../../6.6.2/gcc_64/include/QtCore/qmap.h \
		../../6.6.2/gcc_64/include/QtCore/qshareddata_impl.h \
		../../6.6.2/gcc_64/include/QtCore/qset.h \
		../../6.6.2/gcc_64/include/QtCore/qhash.h \
		../../6.6.2/gcc_64/include/QtCore/qvarlengtharray.h \
		../../6.6.2/gcc_64/include/QtNetwork/QTcpSocket \
		../../6.6.2/gcc_64/include/QtNetwork/qtcpsocket.h \
		../../6.6.2/gcc_64/include/QtCore/qvariant.h \
		../../6.6.2/gcc_64/include/QtCore/q23utility.h \
		../../6.6.2/gcc_64/include/QtCore/QVector \
		../../6.6.2/gcc_64/include/QtCore/qvector.h \
		../../6.6.2/gcc_64/include/QtCore/QTime \
		../../6.6.2/gcc_64/include/QtCore/qdatetime.h \
		../../6.6.2/gcc_64/include/QtCore/qcalendar.h \
		../../6.6.2/gcc_64/include/QtCore/qlocale.h \
		../../6.6.2/gcc_64/include/QtCore/QString \
		../../6.6.2/gcc_64/include/QtCore/QDataStream \
		../../6.6.2/gcc_64/include/QtCore/QMap \
		db_connection.h \
		../../6.6.2/gcc_64/include/QtSql/QSqlDatabase \
		../../6.6.2/gcc_64/include/QtSql/qsqldatabase.h \
		../../6.6.2/gcc_64/include/QtSql/qtsqlglobal.h \
		../../6.6.2/gcc_64/include/QtSql/qtsql-config.h \
		../../6.6.2/gcc_64/include/QtSql/qtsqlexports.h \
		../../6.6.2/gcc_64/include/QtCore/QDebug \
		../../6.6.2/gcc_64/include/QtCore/QCryptographicHash \
		../../6.6.2/gcc_64/include/QtCore/qcryptographichash.h \
		../../6.6.2/gcc_64/include/QtSql/QSqlQuery \
		../../6.6.2/gcc_64/include/QtSql/qsqlquery.h \
		../../6.6.2/gcc_64/include/QtCore/QByteArray \
		../../6.6.2/gcc_64/include/QtSql/QSqlError \
		../../6.6.2/gcc_64/include/QtSql/qsqlerror.h \
		../../6.6.2/gcc_64/include/QtCore/QJsonArray \
		../../6.6.2/gcc_64/include/QtCore/qjsonarray.h \
		../../6.6.2/gcc_64/include/QtCore/qjsonvalue.h \
		../../6.6.2/gcc_64/include/QtCore/qcborvalue.h \
		../../6.6.2/gcc_64/include/QtCore/qcborcommon.h \
		../../6.6.2/gcc_64/include/QtCore/qregularexpression.h \
		../../6.6.2/gcc_64/include/QtCore/qurl.h \
		../../6.6.2/gcc_64/include/QtCore/quuid.h \
		../../6.6.2/gcc_64/include/QtCore/qendian.h \
		../../6.6.2/gcc_64/include/QtCore/QJsonDocument \
		../../6.6.2/gcc_64/include/QtCore/qjsondocument.h \
		../../6.6.2/gcc_64/include/QtCore/QJsonObject \
		../../6.6.2/gcc_64/include/QtCore/qjsonobject.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o server.o server.cpp

moc_server.o: moc_server.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_server.o moc_server.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/opt/server/bin || mkdir -p $(INSTALL_ROOT)/opt/server/bin
	$(QINSTALL_PROGRAM) $(QMAKE_TARGET) $(INSTALL_ROOT)/opt/server/bin/$(QMAKE_TARGET)
	-$(STRIP) $(INSTALL_ROOT)/opt/server/bin/$(QMAKE_TARGET)

uninstall_target: FORCE
	-$(DEL_FILE) $(INSTALL_ROOT)/opt/server/bin/$(QMAKE_TARGET)
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/server/bin/ 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

.SUFFIXES:

